services:
  - type: web
    name: smart-grocery-store
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn django_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_project.settings
      - key: SECRET_KEY
        value: 202418011Ch@tgpt
      - key: DEBUG
        value: 'False'
