databases:
  - name: smartgrocerydb
    plan: free
    databaseName: smartgrocery
    user: smartgrocery

services:
  - type: web
    name: smart-grocery-store
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: python -m gunicorn django_project.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_project.settings
      - key: SECRET_KEY
        value: 202418011Ch@tgpt  # Replace with a secure value in real deployment
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: smartgrocerydb
          property: connectionString
